provinces = {
    1:  {"tr": "Adana",          "en": "Adana",             "gadm": "Adana"},
    2:  {"tr": "Adıyaman",       "en": "Adiyaman",          "gadm": "Adiyaman"},
    3:  {"tr": "Afyonkarahisar", "en": "Afyonkarahisar",    "gadm": "Afyon"},
    4:  {"tr": "Ağrı",           "en": "Agri"},
    5:  {"tr": "Amasya",         "en": "Amasya"},
    6:  {"tr": "Ankara",         "en": "Ankara"},
    7:  {"tr": "Antalya",        "en": "Antalya"},
    8:  {"tr": "Artvin",         "en": "Artvin"},
    9:  {"tr": "Aydın",          "en": "Aydin"},
    10: {"tr": "Balıkesir",      "en": "Balikesir"},
    11: {"tr": "Bilecik",        "en": "Bilecik"},
    12: {"tr": "Bingöl",         "en": "Bingol",            "gadm": "Bingöl"},
    13: {"tr": "Bitlis",         "en": "Bitlis"},
    14: {"tr": "Bolu",           "en": "Bolu"},
    15: {"tr": "Burdur",         "en": "Burdur"},
    16: {"tr": "Bursa",          "en": "Bursa"},
    17: {"tr": "Çanakkale",      "en": "Canakkale",         "gadm": "Çanakkale"},
    18: {"tr": "Çankırı",        "en": "Cankiri",           "gadm": "Çankiri"},
    19: {"tr": "Çorum",          "en": "Corum",             "gadm": "Çorum"},
    20: {"tr": "Denizli",        "en": "Denizli"},
    21: {"tr": "Diyarbakır",     "en": "Diyarbakir"},
    22: {"tr": "Edirne",         "en": "Edirne"},
    23: {"tr": "Elazığ",         "en": "Elazig",            "gadm": "Elazığ"},
    24: {"tr": "Erzincan",       "en": "Erzincan"},
    25: {"tr": "Erzurum",        "en": "Erzurum"},
    26: {"tr": "Eskişehir",      "en": "Eskisehir"},
    27: {"tr": "Gaziantep",      "en": "Gaziantep"},
    28: {"tr": "Giresun",        "en": "Giresun"},
    29: {"tr": "Gümüşhane",      "en": "Gumushane",         "gadm": "Gümüshane"},
    30: {"tr": "Hakkari",        "en": "Hakkari"},
    31: {"tr": "Hatay",          "en": "Hatay"},
    32: {"tr": "Isparta",        "en": "Isparta"},
    33: {"tr": "Mersin",         "en": "Mersin"},
    34: {"tr": "İstanbul",       "en": "Istanbul"},
    35: {"tr": "İzmir",          "en": "Izmir"},
    36: {"tr": "Kars",           "en": "Kars"},
    37: {"tr": "Kastamonu",      "en": "Kastamonu"},
    38: {"tr": "Kayseri",        "en": "Kayseri"},
    39: {"tr": "Kırklareli",     "en": "Kirklareli"},
    40: {"tr": "Kırşehir",       "en": "Kirsehir"},
    41: {"tr": "Kocaeli",        "en": "Kocaeli"},
    42: {"tr": "Konya",          "en": "Konya"},
    43: {"tr": "Kütahya",        "en": "Kutahya",           "gadm": "Kütahya"},
    44: {"tr": "Malatya",        "en": "Malatya"},
    45: {"tr": "Manisa",         "en": "Manisa"},
    46: {"tr": "Kahramanmaraş",  "en": "Kahramanmaras",     "gadm": "K. Maras"},
    47: {"tr": "Mardin",         "en": "Mardin"},
    48: {"tr": "Muğla",          "en": "Mugla"},
    49: {"tr": "Muş",            "en": "Mus"},
    50: {"tr": "Nevşehir",       "en": "Nevsehir"},
    51: {"tr": "Niğde",          "en": "Nigde"},
    52: {"tr": "Ordu",           "en": "Ordu"},
    53: {"tr": "Rize",           "en": "Rize"},
    54: {"tr": "Sakarya",        "en": "Sakarya"},
    55: {"tr": "Samsun",         "en": "Samsun"},
    56: {"tr": "Siirt",          "en": "Siirt"},
    57: {"tr": "Sinop",          "en": "Sinop"},
    58: {"tr": "Sivas",          "en": "Sivas"},
    59: {"tr": "Tekirdağ",       "en": "Tekirdag"},
    60: {"tr": "Tokat",          "en": "Tokat"},
    61: {"tr": "Trabzon",        "en": "Trabzon"},
    62: {"tr": "Tunceli",        "en": "Tunceli"},
    63: {"tr": "Şanlıurfa",      "en": "Sanliurfa"},
    64: {"tr": "Uşak",           "en": "Usak"},
    65: {"tr": "Van",            "en": "Van"},
    66: {"tr": "Yozgat",         "en": "Yozgat"},
    67: {"tr": "Zonguldak",      "en": "Zonguldak",         "gadm": "Zinguldak"},
    68: {"tr": "Aksaray",        "en": "Aksaray"},
    69: {"tr": "Bayburt",        "en": "Bayburt"},
    70: {"tr": "Karaman",        "en": "Karaman"},
    71: {"tr": "Kırıkkale",      "en": "Kirikkale",         "gadm": "Kinkkale"},
    72: {"tr": "Batman",         "en": "Batman"},
    73: {"tr": "Şırnak",         "en": "Sirnak"},
    74: {"tr": "Bartın",         "en": "Bartin",           "gadm": "Bartın"},
    75: {"tr": "Ardahan",        "en": "Ardahan"},
    76: {"tr": "Iğdır",          "en": "Igdir",             "gadm": "Iğdır"},
    77: {"tr": "Yalova",         "en": "Yalova"},
    78: {"tr": "Karabük",        "en": "Karabuk",           "gadm": "Karabük"},
    79: {"tr": "Kilis",          "en": "Kilis"},
    80: {"tr": "Osmaniye",       "en": "Osmaniye"},
    81: {"tr": "Düzce",          "en": "Duzce",             "gadm": "Düzce"},
}

tr_to_id = {v["tr"]: k for k, v in provinces.items()}
en_to_id = {v["en"]: k for k, v in provinces.items()}
id_to_tr = {k: v["tr"] for k, v in provinces.items()}
id_to_en = {k: v["en"] for k, v in provinces.items()}
id_to_gadm = {k: v.get("gadm", v["en"]) for k, v in provinces.items()}
gadm_to_id = {v.get("gadm", v["en"]): k for k, v in provinces.items()}

nuts3_to_id = {
    "TR100": 34, "TR211": 59, "TR212": 22, "TR213": 39,
    "TR221": 10, "TR222": 17, "TR310": 35, "TR321":  9,
    "TR322": 20, "TR323": 48, "TR331": 45, "TR332":  3,
    "TR333": 43, "TR334": 64, "TR411": 16, "TR412": 26,
    "TR413": 11, "TR421": 41, "TR422": 54, "TR423": 81,
    "TR424": 14, "TR425": 77, "TR510":  6, "TR521": 42,
    "TR522": 70, "TR611":  7, "TR612": 32, "TR613": 15,
    "TR621":  1, "TR622": 33, "TR631": 31, "TR632": 46,
    "TR633": 80, "TR711": 71, "TR712": 68, "TR713": 51,
    "TR714": 50, "TR715": 40, "TR721": 38, "TR722": 58,
    "TR723": 66, "TR811": 67, "TR812": 78, "TR813": 74,
    "TR821": 37, "TR822": 18, "TR823": 57, "TR831": 55,
    "TR832": 60, "TR833": 19, "TR834":  5, "TR901": 61,
    "TR902": 52, "TR903": 28, "TR904": 53, "TR905":  8,
    "TR906": 29, "TRA11": 25, "TRA12": 24, "TRA13": 69,
    "TRA21":  4, "TRA22": 36, "TRA23": 76, "TRA24": 75,
    "TRB11": 44, "TRB12": 23, "TRB13": 12, "TRB14": 62,
    "TRB21": 65, "TRB22": 49, "TRB23": 13, "TRB24": 30,
    "TRC11": 27, "TRC12":  2, "TRC13": 79, "TRC21": 63,
    "TRC22": 21, "TRC31": 47, "TRC32": 72, "TRC33": 73,
    "TRC34": 56,
}
id_to_nuts3 = {v: k for k, v in nuts3_to_id.items()}